### ISSUE TITLE
Recipes issue

### ISSUE THREAD

**Issue by rickselby** [MouseyPounds/stardew-checkup#1]
> player knows 70 recipe(s) and has cooked 71 of them; there are 71 total recipes.

I'm missing Artichoke Dip - I missed the recipe the first time around. 605 is not in `recipesCooked`.

However... `recipesCooked` believes I've cooked 5 Large Eggs (174)!

Would it be possible to check that each cooked recipe's ID is actually a recipe, to get a correct count?

Thanks!

**Comment by MouseyPounds** [comment]
Sanity-checking the recipe ID has been added in version 2.0.1. Thanks for the suggestion.
