### ISSUE TITLE
Bug with Secret Note #14

### ISSUE THREAD

**Issue by Zamiell** [MouseyPounds/stardew-checkup#9]
Steps to reproduce:

1) Start a new save file.
2) Sleep once to go to Spring 2.
3) Go to the Community Center and hoe the [Stone Junimo](https://stardewvalleywiki.com/Stone_Junimo).
4) Delete the Stone Junimo.
5) Sleep.
6) Use [Stardew Checkup](https://mouseypounds.github.io/stardew-checkup/).

It displays that "Reward from Secret Note 14" is left to find, which is false.

Note that if you do not delete the Stone Junimo, and do everything else the same, Stardew Checkup seems to work just fine.

Also note that it does not seem to be possible to get another Stone Junimo (after you delete it). If you go back to the spot and hoe it, then nothing happens.

**Comment by MouseyPounds** [comment]
The only way I can detect if the note reward was found is to search containers and placed objects for the Stone Junimo. If somebody digs it up and then deletes it, there really isn't anything I can do. I can't imagine this is a common occurrence, but if you have some better idea for detecting the reward, I am open to hear it.

**Comment by Zamiell** [comment]
As I've said above, when I go back to hoe the same spot on the day after I have deleted the Stone Junimo, I am not able to re-hoe another one. Thus, this implies that this note condition is baked into the XML somewhere.

However, on my current save file, around 3 seasons have passed since I first destroyed the Stone Junimo. As a test, I went back to try and hoe it again, and it did actually give me a 2nd Stone Junimo. Thus, I hypothesize that it might function like a crop, where it takes a certain number of days to "grow back".

With respect to this issue, I think we should close it, but I think it would be helpful to change the description:

`Reward from Secret Note 14`
-->
`Reward from Secret Note 14 (will show as incomplete if the Stone Junimo is destroyed)`

This explicitly lets players know about the condition here, which is useful because I imagine that plenty of players destroy all furniture (as it cannot be sold and serves no min-max purpose). Are there any other Secret Note conditions like this?

As a completely separate issue, please fix all of the wiki links for the Secret Notes section, as they seem to be broken.

And while I'm at it, can you please add links for the heart events? e.g. "7♥" under Shane's section links to `https://stardewvalleywiki.com/Shane#Seven_Hearts_I`
This would be tremendously helpful.

**Comment by MouseyPounds** [comment]
Based upon StardewValley.Locations.Town:DayUpdate, the game replaces the stone junimo every year on Spring 2 so long as you are not a Joja member and the location is clear. So even if you destroy it, it should be possible to get it again later. I can look at some extra phrasing for it though. I will also look at links for the heart events.

**Comment by Zamiell** [comment]
Thank you!

**Comment by Zamiell** [comment]
I guess I'll close this now since the site has text informing the player that it is inaccurate.
